### ISSUE TITLE
Fix better macro for compiling code depending on HAL version

### ISSUE THREAD

**Issue by emilwestergren** [vidhance/android-camera-wrapper#22]
We need a more scalable method of separating code specific to HAL versions than the current one.

`#define HAL_VERSION_MAJOR 3`
`#define HAL_VERSION_MINOR 2`
```c++
#define HAL_VERSION(MAJOR,MINOR)  HAL_VERSION_MAJOR == MAJOR && HAL_VERSION_MINOR == MINOR
```
`#if HAL_VERSION(3, 2)`
`#if HAL_MAJOR_VERSION == 3`

@sebastianbaginski do you have any suggestions here?

**Comment by sebastianbaginski** [comment]
Yes something like this. I saw people defining macros for it like
```C++
#define VERSION_MAJOR 5
#define VERSION_MINOR 2
#define VERSION_PATCH 11
#define VERSION_TEST(major, minor, patch) ((major<<16)|(minor<<8)|(patch))
#define CURRENT_VERSION VERSION_TEST(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)
```
and later you can check like
```C++
#if CURRENT_VERSION >= VERSION_TEST(5, 0, 0)
...
```
